### ISSUE TITLE
Criar pagina do docs

### ISSUE THREAD

**Issue by Bumbleblo** [fga-eps-mds/Alohomora#12]
**Descreva a solução que gostaria**

É necessário que tenhamos um local para centralizar as informações sobre o software e também apresentar o produto.

**Funcionalidades requeridas**

- [x] Elaborar uma forma de centralizarmos e subir ferramentas se necessário
- [ ] Adicionar estrutura de arquivos ao repositório
- [X] Fazer deploy na branch `gh-pages`

**Contexto Adicional**

Sugiro fortemente que usem o [mkdocs](https://www.mkdocs.org/)

**Comment by Bumbleblo** [comment]
@mateusnr começou a elaborar essa issue.

**Comment by Bumbleblo** [comment]
A situação atual é que temos o mkdocs na branch porém ainda não configuramos a brnach gh-pages.

**Comment by Bumbleblo** [comment]
@mateusnr conseguiu subir o mkdocs e já esta em deployment em https://fga-eps-mds.github.io/2019.2-Grupo6/.

**Comment by mateusnr** [comment]
Reabri a issue pois estarei modificando a estrutura e adicionando algumas informações

**Comment by Bumbleblo** [comment]
Por que não apenas criar outra issue ? Não ficou nenhuma dependência dessa

**Comment by mateusnr** [comment]
Não achei que o template estava muito bom da primeira vez, acabei decidindo reabrir a issue pra melhroar algumas coisas
