### ISSUE TITLE
Elaborar estrutura do condominio

### ISSUE THREAD

**Issue by Bumbleblo** [fga-eps-mds/Alohomora#20]
**Descreva a solução que gostaria**

O condominio é organizado em blocos e apartamentos. A ideia dessa tarefa é escrever essa estrutura e disponibilizar ela em uma API.

**Funcionalidades requeridas**

- [x] Escrever as models
- [x] Disponibilizar uma maneira de criar elas via http.
- [ ] testes

**Contexto Adicional**

**Comment by baraky** [comment]
Conseguimos implementar a maiora das requisições, porém estamos com dificuldades na parte de testar o GraphQL (queries, mutation, etc...). Há pouca documentação na web e oque tem é **muito** fraco.

**Comment by higton** [comment]
```
from django.test import (TestCase, )
from graphene.test import Client

from ...schema import schema
from portariaVirtual.accounts.models import User

class GraphQLTestCase(TestCase):
    def setUp(self):
        self._client = Client(schema)
    def query(self, query: str):
        resp = self._client.execute(query)
        return resp


    def test_create_flashcard(self):

        mutation = '''
        mutation{
          createUser(
            email: "matpaul@oi",
            password: "1234",
          ){ user{
             username
             email
             password
          }
          }
        }
        '''
        response = self.query(query=mutation)
        self.assertEqual(User.objects.count(), 1)
        self.assertEqual(User.objects.get(id=1).email, 'matpaul@oi')

```

Aqui está uma mutation do graphene testada, utilizei este repositorio como exemplo [.link para o repositorio](https://github.com/wysockipiotr/flashback-gql/blob/master/flashback/core/tests.py), mesmo que não seja com o pytest esse repositório me ajudou muito. Espero que te ajude também.
