### ISSUE TITLE
Testar implementações de autenticação por voz

### ISSUE THREAD

**Issue by Bumbleblo** [fga-eps-mds/Alohomora#22]
**Descreva a solução que gostaria**

Nas issues #11  e #9 sugiram algumas tecnologias que podemos utilizar para lidar com o problema de voz. Essa tarefa é para explorar soluções similares ou implementações alternativas para resolver o problema de verificação de pessoas (*saber se a voz gravada é a mesma da fornecida).

**Funcionalidades requeridas**

- [x] Testar implementação <metodo aqui>
- [ ] Testar solução proposta pela Microsoft em 2010

**Contexto Adicional**

Colocar artigo da microsoft aqui

**Comment by Bumbleblo** [comment]
Encontrei esse [repositório](https://github.com/pierre-rouanet/dtw/blob/master/dtw/dtw.py) que já implementa a função em python. 

Esses [vídeos](http://www.speech.zone/exercises/dtw-in-python/) mostram como fazer passo a passo do algoritmo .

**Comment by Bumbleblo** [comment]
Consegui implementar o algoritmo: 

```python3

import numpy as np

# optimal warping path between x and y is p*

# dtw = min{Cp(X,Y) | p is an (N, M) - warping path}

# dp method d(n, m) = min( d(n-1, m-1), d(n-1,m), d(n,m-1)} + c(Xn, Ym)
def dtw(serie1, serie2):

    d = np.zeros((len(serie1), len(serie2)))
    
    x, y = d.shape

    d[0, 0] = abs(serie1[0] - serie2[0])

    slice_serie_1 = d[:, 0]

    for i in range(1, x):
        slice_serie_1[i] = abs(serie1[i] - serie2[0]) + d[i-1, 0]


    slice_serie_2 = d[0, :]
    for j in range(1, y):
        slice_serie_2[j] = abs(serie1[0] - serie2[j]) +  d[0, j-1]
        
    for i in range(1, x):
        for j in range(1, y):
            d[i, j] = abs(serie1[i] - serie2[j]) + min(d[i-1, j-1], d[i-1, j], d[i, j-1])

    return d

def evaluate(dtw_matrix):

    x, y = dtw_matrix.shape


    x-=1
    y-=1

    value = dtw_matrix[x,y]
    while(x and y):

        new_array = np.array(
            [
                dtw_matrix[x-1, y],
                dtw_matrix[x-1, y-1],
                dtw_matrix[x, y-1]
            ]
        )

        index = np.argmin(new_array)

        value+=new_array[index]

        if index == 0:
            x-=1
        elif index ==1:
            x-=1
            y-=1
        else:
            y-=1

        
    return value

if __name__ == '__main__':

    #t1 = [1,2,3,4]
    #t2 = [2,3,4,5]

    t1 = [1,6,2,3,0,9,4,3,6,3]
    t2 = [1,3,4,9,8,2,1,5,7,3]

    result = dtw(t1,t2)
    n, m = result.shape

    print(result)
    print(result[n-1, m-1])
    print(evaluate(result))

```

Usei o vídeo desse cara para debugar, a implementação é O(n*m). Existem formas de otimizar mas vamos primeiro concentrar em fazer isso funcionar na autenticação para depois olharmos esses pontos.

**Comment by higton** [comment]
Muito bom! também encontrei alguns repositorios que ulitizam dtw [link](https://github.com/Linzecong/MFCC-DTW) e [link](https://github.com/amitchone/ASR)(esse aqui utiliza fastdwt). 
Vou dar uma olhada nos videos e estudar esse algoritmo.

**Comment by VictorJorgeFGA** [comment]
A referência do tutorial de conversão dos .wav pra vetores de frequência: https://www.pythonforengineers.com/audio-and-digital-signal-processingdsp-in-python/

Talvez, ainda possa ser útil aqui pra gente.

**Comment by Bumbleblo** [comment]
Show, hoje conversei com um especialista da área de sinais. A encaminhamento que tive foi de realizar o teste do dtw em uma base para ver como ele performa. Além da implementação N^2 nós temos que realizar N comparações do algoritmo (temos que comparar o audio coletado com todos os outros da base de dados). Ou seja, precisamos testar essa estratégia.

Para mim, a última coisa que esta faltando nessa issue é a estratégia de classificação. O DTW ta implementado porém o método por si só não resolve nada, precisamos de uma heuristica de classificação. Se vocês puderem testar com várias vozes diferentes e tentar procurar pelo o menor valor do DTW eu acredito que será um bom começo.

Acredito que com isso temos uma baseline na autenticação de voz.

**Comment by Bumbleblo** [comment]
> Muito bom! também encontrei alguns repositorios que ulitizam dtw [link](https://github.com/Linzecong/MFCC-DTW) e [link](https://github.com/amitchone/ASR)(esse aqui utiliza fastdwt).
> Vou dar uma olhada nos videos e estudar esse algoritmo.

Acredito que são ótimos para realizar os testes. Existem algumas funções que usaremos nos próximos passos.

**Comment by Bumbleblo** [comment]
> A referência do tutorial de conversão dos .wav pra vetores de frequência: https://www.pythonforengineers.com/audio-and-digital-signal-processingdsp-in-python/
> 
> Talvez, ainda possa ser útil aqui pra gente.

Show, consegui criar um código que já pega o áudio direto. Pode ser que seja útil de alguma forma.

```python3
import numpy as np
from tqdm import tqdm
import time
import sounddevice as sd

# optimal warping path between x and y is p*

# dtw = min{Cp(X,Y) | p is an (N, M) - warping path}
# dynamic time warping 
# dp method d(n, m) = min( d(n-1, m-1), d(n-1,m), d(n,m-1)} + c(Xn, Ym)
def dtw(serie1, serie2):

    d = np.zeros((len(serie1), len(serie2)))
    
    x, y = d.shape

    d[0, 0] = abs(serie1[0] - serie2[0])

    slice_serie_1 = d[:, 0]

    for i in tqdm(range(1, x)):
        slice_serie_1[i] = abs(serie1[i] - serie2[0]) + d[i-1, 0]


    slice_serie_2 = d[0, :]
    for j in tqdm(range(1, y)):
        slice_serie_2[j] = abs(serie1[0] - serie2[j]) +  d[0, j-1]
        
    for i in tqdm(range(1, x)):
        for j in range(1, y):
            d[i, j] = abs(serie1[i] - serie2[j]) + min(d[i-1, j-1], d[i-1, j], d[i, j-1])

    return d

def evaluate(dtw_matrix):

    x, y = dtw_matrix.shape


    x-=1
    y-=1

    value = dtw_matrix[x,y]
    while(x and y):

        new_array = np.array(
            [
                dtw_matrix[x-1, y],
                dtw_matrix[x-1, y-1],
                dtw_matrix[x, y-1]
            ]
        )

        index = np.argmin(new_array)

        value+=new_array[index]

        if index == 0:
            x-=1
        elif index ==1:
            x-=1
            y-=1
        else:
            y-=1

        
    return value

if __name__ == '__main__':

    #t1 = [1,2,3,4]
    #t2 = [2,3,4,5]

    t1 = [1,6,2,3,0,9,4,3,6,3]
    t2 = [1,3,4,9,8,2,1,5,7,3]

    result = dtw(t1,t2)
    n, m = result.shape

    print(result)
    print(result[n-1, m-1])
    print(evaluate(result))

    fs = 1000    # 48100
    seconds = 2

    print("Gravando A")
    a = sd.rec(int(seconds*fs), samplerate=fs, channels=1)

    time.sleep(10)

    print("Gravando B")
    b = sd.rec(int(seconds*fs), samplerate=fs, channels=1)

    time.sleep(3)
    print(a.shape)
    print(b.shape)

    sd.play(a, fs)
    sd.play(b, fs)


    matrix = dtw(a,b)

    print(f'Valor final: {evaluate(matrix)}')
```
