### ISSUE TITLE
Criar mutation para cadastro de um usuário

### ISSUE THREAD

**Issue by Bumbleblo** [fga-eps-mds/Alohomora#33]
**Descreva a solução que gostaria**

Criar a mutation que facilite na criação de um usuário.

**Funcionalidades requeridas**

- [ ] Escrever a classe mutation que cadatre o usuário

**Contexto Adicional**

Adicionem outros contextos e fotos das telas

**Comment by Bumbleblo** [comment]
Como que ta indo a evolução desta atividade, precisa de ajuda com alguma coisa ?

**Comment by RodrigoTCLima** [comment]
Estive muito ocupado e só poderei começar a mexer agora. Se houver algum problema, avisarei.

**Comment by Bumbleblo** [comment]
Da uma olhada no comentário da @AlineLermen

**Comment by Bumbleblo** [comment]
Foi realizado na issue #37
