### ISSUE TITLE
Relacionar morador com o apartamento

### ISSUE THREAD

**Issue by Bumbleblo** [fga-eps-mds/Alohomora#35]
**Descreva a solução que gostaria**

Escrever a relação apartamento morador.

**Funcionalidades requeridas**

- [ ] Adicionar field de relação

**Comment by Bumbleblo** [comment]
Olá pessoal, estão tendo alguma dificuldade com essa issue ? Me digam o que estão pensando sobre essa tarefa. Se tiverem alguma dificuldade eu posso ajudar vocês!

**Comment by higton** [comment]
Como eu estava muito ocupado com a outra issue #37, não deu muito tempo para pesquisar direito sobre as relações. Mesmo assim, eu tentei criar com o ManyToManyField, mas não consegui colocá-lo para funcionar. Essa foi a mensagem de erro:
"message": "Received incompatible instance \"accounts.User.None\"."
