### ISSUE TITLE
Utilizar o dtw para realizar a autenticação por voz

### ISSUE THREAD

**Issue by Bumbleblo** [fga-eps-mds/Alohomora#36]
**Descreva a solução que gostaria**

Escrever um classificador simples (pegar o menor valor possível entre os dtws) e testar esse algoritmo para realizar autenticação por voz.

**Funcionalidades requeridas**

- [ ] Escrever o código de classificação
- [ ] Realizar um experimento gravando várias vozes e testando o algoritmo.

**Comment by VictorJorgeFGA** [comment]
Por acaso achei o fastDTW já implementado. A função promete rodar com complexidade O(N), que no caso de uma amostra de 1000 valores, o algoritmo roda ao máximo 1000x mais rápido. Dessa forma a preocupação agora fica voltada pra extração de dados da voz de forma eficiente. 

https://pypi.org/project/fastdtw/

**Comment by Bumbleblo** [comment]
Na issue #22 eu usei o soundevice para realizar a extração do som. Consultei alguns especialistas da área e eles recomendaram não diminuir o atributo fs além do que 4000

**Comment by VictorJorgeFGA** [comment]
Pra um framerate de 41k o audio fica em uma qualidade bem aceitável, porém, mesmo o fast dtw está demorando 1 minuto pra computar a distância nos vetores gerados. Pro valor mínimo que você sugeriu (4000), o audio fica péssimo, mas o fast dtw computa tudo em aproximadamente 10 segundos. O computador que usei nos testes tem um i5, provavelmente uma das versões mais fracas da serie 2xxx, com Ram de 1333Mhz. Acredito que o cenário de um possível cliente seja aproximadamente esse. Vou pesquisar agora sobre como funcionaria se transformássemos pro domínio da frequência. Acho que assim vamos conseguir deixar o tamanho do array fixo na ordem de 10ˆ3 independentemente do framerate escolhido na captura.

**Comment by VictorJorgeFGA** [comment]
Realizei os testes.

Comparei audio da minha voz em que deveria ter um bom match, e audios com a voz distorcida, ou com outros sons. 

Resultado: Os valores não fizeram o menor sentido.

Procurei saber mais sobre que tipos de dados exatamente o vetor de "dados" de voz guarda no seu código, e acabei só me frustrando com a falta de documentação dessas libs do python. Busquei novos meios, tais como: Salvar arquivos .wav e abrir com outra biblioteca (nao deu certo). Utilizar, cegamente, a Fast Fourrier Transform nesses dados e comparar esses novos dados com o DTW. Resultado: Nada funcionou. Arrisco dizer que piorou tudo.

Depois de tudo isso, procurei pdf acadêmicos que abordam maneiras de implementar um speaker recognition passo a passo. Com essa pesquisa descobri que dos 8 passos que compõem o sistema de speaker recognition, pulamos 7. Sem esses 7 passos que antecedem o uso do DTW, é como se estivéssemos tentando construir um arranha-céu empilhando um monte de areia e pedra. Simplesmente é impossível.

**Comment by VictorJorgeFGA** [comment]
O que a gente conversou hoje foi sobre utilizar o Microsoft Azure mesmo, ou qualquer outro serviço  pronto que funcione bem. Testamos o sistema do Azure e o resultado é satisfatório. Porém o novo problema aqui é conseguirmos a versão minimamente 0800 do serviço com nossas credenciais de estudante. Tentei fazer isso aqui, mas por enquanto só encontrei problemas. 

Acho que seria bom se conversássemos com a Carla pra ver se ela pode nos ajudar a conseguir essa API de forma gratuita, ou qualquer outra que funcione.

**Comment by Bumbleblo** [comment]
Primeiramente a voz não é para fazer sentido para ouvido humano mesmo. O valor de 4k é apropriado para processamento. Gostaria que mostrasse o experimento, pelo o que você me falou você estava olhando os valores do dwt, se foi isso: Este não é o propósito. 

Relembrando o objetivo aqui é realizar a classificação fazendo o dtw. Ao que me parece vocês tão ignorando completamente a direção que estou colocando para essa atividade. 

Como coloquei na issue e já ressaltei pessoalmente: o objetivo é avaliar o método, não descobrir formatos de arquivos, usar FFT sem ter a minima noção do método ou qualquer outra coisa do tipo. No caso de encontrar uma API que faça esse trabalho, show de bola, no entanto até aqui não vi nenhuma que faça a autorização por voz e seja open source.

Por último mas ainda assim muito importante, bote referências. Ficar na issue divagando sobre possibilidades sem mostrar código, referência, papers ou links para as APIs que testaram é perca de tempo. A discussão fica no mundo das ideias além do avaliador perder muito tempo apenas procurando o conteúdo que esta discutido.

**Comment by Bumbleblo** [comment]
Podemos avaliar todos esses métodos e alternativa, o que quero ressaltar é que nesse momento não é esta issue que foi atribuída.

**Comment by VictorJorgeFGA** [comment]
Ok. Entao antes de seguir com a issue preciso tirar algumas duvidas: Faco o classificador me baseando no vetor de dados crus ao abrir um arquivo de audio num vetor? Por exemplo, com o sounddevice pra captura instantanea, ou o scipy com o wavfile - ambos armazenam os dados crus em um vetor.
   O problema que quero apontar aqui e que existem alguns passos necessarios antes de aplicar o DTW nos dados ( www.encurtador.com.br/swT46 ) que parecem ser bem desafiadores de se aplicar. Quanto aos valores duvidosos do DTW, nao vejo sentido em abstrair esses valores, afinal de contas o proprio DTW retorna a distancia entre as duas series de dados. Se o proprio DTW nao oferece um padrao nas saidas com as entradas cruas, nao consigo pensar em um cenario em que um classificador poderia ser criado com essas saidas.

**Comment by Bumbleblo** [comment]
Essa técnica citada acrescenta uma passo apenas para extração que é o MFCC. Essa etapa será escopo da próxima sprint no entanto estou esperando o resultado o DTW em cima da série inicial.

**Comment by VictorJorgeFGA** [comment]
Deixa eu ver se entendi: devo criar um classificador ignorando por enquanto a falta do MFCC? Porque ate entao eu pensava que eu deveria fazer um classificador que ja funcionasse com as entradas cruas, o que com os testes que eu fiz ja fica evidente que nao da certo. Vou refazer os testes de classificacao e colar aqui o codigo e os resultados, assim poderemos tirar conclusoes com mais clareza.

**Comment by VictorJorgeFGA** [comment]
Versão simples implementada:
https://github.com/VictorJorgeFGA/voice_comparator
