### ISSUE TITLE
Usar autenticação via graphql

### ISSUE THREAD

**Issue by Bumbleblo** [fga-eps-mds/Alohomora#37]
**Descreva a solução que gostaria**

A autenticação via JWT no rest realizar a restrição de acesso nas models da aplicação. Sendo assim é necessário um mecanismo para autenticação dentro do graphql.

**Funcionalidades requeridas**

- [ ] Usar o graphql-jwt
- [ ] Escrever as mutations para o tokens
- [ ] Realizar restrição de acesso na estrutura do condominio

**Comment by higton** [comment]
Eu acho que consegui fazer a autenticação dentro do graphql, utilizando a ideia comentada pela   @AlineLermen  na issue #21 e a documentação do django sobre autenticação customizada [.link da documentação ](https://docs.djangoproject.com/en/2.2/topics/auth/customizing/). Que é "trabalhar em um caso que a gente utilizasse a model User do Django e relacionasse ela com uma model profile, onde teria as informações extras, como telefone, apartamento e bloco".

Na models.py do app 
```
from django.db import models
from django import forms
from django.contrib.auth.models import AbstractUser, BaseUserManager

class UserManager(BaseUserManager):
    def create_user(self, email, password=None, **kwars):
        if not email:
            raise ValueError('Users must have an email address')
        user = self.model(
            email=self.normalize_email(email),
        )
        user.set_password(password)
        user.save(using=self._db)
        return user
class User(AbstractUser):
    email = models.CharField(max_length = 20, unique=True)
    phone = models.CharField(max_length = 9, unique=True)
    complete_name = models.CharField(max_length = 80, unique=True)

    objects = UserManager()
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []
    def __str__(self):
        return self.email
```
AbstractUser é uma classe abstrata, então você pode herdar do User model padrão como alguns fields já definidos. Apartir disso, eu posso adicionar os meus próprios fields e métodos.
UserManager é utilizado pois eu criei meu User com field diferente, coloquei email no lugar de username, como mostrado em "USERNAME_FIELD = 'email' ".

No schema.py do app

```
from django.contrib.auth import get_user_model

import graphene
from graphene_django import DjangoObjectType


class UserType(DjangoObjectType):
    class Meta:
        model = get_user_model()


class CreateUser(graphene.Mutation):
    user = graphene.Field(UserType)

    class Arguments:
        complete_name = graphene.String(required=True)
        username = graphene.String(required=True)
        password = graphene.String(required=True)
        email = graphene.String(required=True)

    def mutate(self, info, username, complete_name, password, email):
        user = get_user_model()(
            complete_name=complete_name,
            username=username,
            email=email,
        )
        user.set_password(password)
        user.save()

        return CreateUser(user=user)


class Mutation(graphene.ObjectType):
    create_user = CreateUser.Field()

class Query(graphene.ObjectType):
    users = graphene.List(UserType)

    def resolve_users(self, info):
        return get_user_model().objects.all()
```
Esse schema é o mesmo desse site [.link para o site](https://www.howtographql.com/graphql-python/4-authentication/)
Eu utilizei get_user_model invés do user model. Pois, como explicado na documentação do django se você referenciar o User diretamente, seu código não vai fucionar onde o AUTH_USER_MODEL é utilizado para um user diferente 
"If you reference User directly (for example, by referring to it in a foreign key), your code will not work in projects where the AUTH_USER_MODEL setting has been changed to a different user model."

**Comment by Bumbleblo** [comment]
Show de bola, percebi que não estão usando o [django-graphql](http://docs.graphene-python.org/projects/django/en/latest/) talvez isso possa ser mais fácil de trabalhar do que com o graphene diretamente.

**Comment by Bumbleblo** [comment]
Gostaria que subisse um PR o mais rápido possível para que eu possa compartilhar analisar o problema com vocês.

**Comment by AlineLermen** [comment]
Fiz o PR, porém ainda não abrange todas as funcionalidades requeridas na issue.
Fiquei com uma dúvida: utilizando o código que o @higton comentou, não estamos resolvendo parte da issue [33](https://github.com/fga-eps-mds/Alohomora/issues/33), porque acabamos escrevendo a mutation para criar um usuário?

**Comment by Bumbleblo** [comment]
Acredito que sim

**Comment by higton** [comment]
Não consegui implementar os testes unitários relacionados à autenticação, o que muito provavelmente deve estar relacionada a minha falta de conhecimento do assunto. Vou dar uma lida na documentação do django(oque eu devia ter feito muito tempo atrás) para entender melhor os conceitos.
