### ISSUE TITLE
Escrever a primeira versão do documento de visão

### ISSUE THREAD

**Issue by Bumbleblo** [fga-eps-mds/Alohomora#38]
**Descreva a solução que gostaria**

O documento visão ele serve pra sincronizar a visão da equipe quanto a um projeto, nesse documento devemos explicar a nossa proposta de solução, procurar soluções existentes e elaborar um pouco sobre questões particulares do projeto.

**Funcionalidades requeridas**

- [ ] Escrever o documento inicial 
- [ ] Expor esse documento no mkdocs

**Comment by Bumbleblo** [comment]
Onde posso acompanhar o trabalho do documento de visão ? Poderia colocar o link aqui (caso esteja usando google docs) ou subir o documento já em um branch em markdown ?

**Comment by AlineLermen** [comment]
Documento de visão em andamento: https://docs.google.com/document/d/1lh-mIvpZnBkyzfJd6KpY5puh-WCVwCeuL_sie4Xn1nE/edit?usp=sharing

**Comment by mateusnr** [comment]
Algumas mudanças que serão necessárias no documento de visão: 

- O sumário não está quebrando a linha corretamente
- Os tópicos 2.2 e 2.3 estão incompletos
- No tópico 3.6, adicione o campo Interesse e o preencha
- No tópico 4.2, imagino que um nome melhor pro tópico seria "Resumo de Recursos". Além disso, adicionar mais benefícios para o usuário
- Descrever o tópico 4.4 quando a licença do projeto for definida
- O tópico 5 (Recursos do Produto) tem que ser preenchido
- No tópico 6, descrever melhor as restrições de uso, adicionar restrições de implementação, restrições externas e restrições de design
