### ISSUE TITLE
Criar o bot no telegram

### ISSUE THREAD

**Issue by Bumbleblo** [fga-eps-mds/Alohomora#39]
**Descreva a solução que gostaria**

Criar o bot no telegram e criar a mensagem de introdução do projeto.

**Funcionalidades requeridas**

- [x] Criar token do telegram
- [x] Escolhar um biblioteca python para interagir com a API 
- [x] Criar a interação de introdução

**Comment by Bumbleblo** [comment]
Ontem ficou claro para equipe que essa atividade já estava quase que completa. Gostaria que os participantes da issue pudessem colocar informações aqui mostrando o que fizeram.

**Comment by baraky** [comment]
Então, criei o bot no telegram com o nome de 'Alohomora' (@AlohoBot), peguei o token e implementei um código, utilizando a API [python-telegram-bot](https://github.com/python-telegram-bot/python-telegram-bot), que ao usuário digitar '/start' o bot apresenta uma mensagem de boas vindas.

```
import logging

from telegram.ext import Updater, CommandHandler, MessageHandler, Filters

logging.basicConfig(format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
                            level=logging.INFO)


logger = logging.getLogger(__name__)


def start(update, context):
    update.message.reply_text("Olá, bem vindo ao bot do Alohomora, o que posso ajudar?")


if __name__ == '__main__':

    token = '959215527:AAG3K2izQIOGmi82pwFnWyGvr0flkq0K3do'

    updater = Updater(token, use_context=True)

    dp = updater.dispatcher

    dp.add_handler(CommandHandler("start", start))

    updater.start_polling()

    updater.idle()    
```

**Comment by mateusnr** [comment]
@baraky Token de bot não se publica em repositório público, recomendo que você crie outro token para o bot

**Comment by baraky** [comment]
Entendi, criei outro token, obrigado!

**Comment by mateusnr** [comment]
Seria interessante fazer logging dos erros, um exemplo fornecido pelo próprio `python-telegram-bot` para fazer isso: https://github.com/python-telegram-bot/python-telegram-bot/blob/master/examples/echobot2.py
