### ISSUE TITLE
Realizar deploy da aplição 

### ISSUE THREAD

**Issue by Bumbleblo** [fga-eps-mds/Alohomora#41]
**Descreva a solução que gostaria**

Realizar o deploy da aplicação em alguma plataforma.

**Funcionalidades requeridas**

- [ ] Configurar a plataforma 
- [ ] Gerenciar a secret key do projeto
- [ ] Configurar fase de deploy

**Comment by Bumbleblo** [comment]
Como que ta indo a evolução desta atividade, precisa de ajuda com alguma coisa ?

**Comment by BordaLorde** [comment]
To estudando como implementar o negocio do coveralls ainda, to meio enrolado mas acredito que saia tudo
