### ISSUE TITLE
MKdocs não esta configurado para Alohomora

### ISSUE THREAD

**Issue by Bumbleblo** [fga-eps-mds/Alohomora#44]
**Descreva o bug**

O site apresenta erro 404 assim que acessado.

**Para reproduzir**

Entra no site: https://fga-eps-mds.github.io/2019.2-Grupo6/

**Comment by mateusnr** [comment]
@Bumbleblo esse link está desatualizado pois ele redireciona para o nome antigo do repositório, que era `2019.2-Grupo6`, para acessar a wiki com o nome mudado, é só alterar o path pro nome do repositório atual (ou seja, de https://fga-eps-mds.github.io/2019.2-Grupo6/ vira https://fga-eps-mds.github.io/Alohomora/)

**Comment by mateusnr** [comment]
O link da descrição do projeto foi arrumado
