### ISSUE TITLE
Escolher o nome do projeto

### ISSUE THREAD

**Issue by Bumbleblo** [fga-eps-mds/Alohomora#7]
**Contexto**

O projeto precisa de um nome. Vamos discutir aqui.

**Contexto Adicional**

Lembrem que tem a mafia do + 

https://github.com/orgs/QueroMais/dashboard
https://github.com/fga-eps-mds/2017.2-Receita-Mais
https://github.com/fga-eps-mds/2019.1-MaisMonitoria
https://github.com/fga-eps-mds/2017.2-MerendaMais
https://github.com/fga-eps-mds/2019.1-MaisMonitoria-FrontEnd
https://github.com/fga-eps-mds/2019.1-MaisMonitoria-ApiMonitorias
https://github.com/fga-eps-mds/2016.1-avalia_mais
https://github.com/fga-eps-mds/2017.2-MerendaMais-Backend

**Comment by Bumbleblo** [comment]
Acredito realmente no Portaria+.

**Comment by Bumbleblo** [comment]
Gostaria de ouvir a opnião dos desenvolvedores de MDS!

**Comment by baraky** [comment]
Estamos pensando em **Alohomora** (feitiço de Harry Potter que abre/destranca portas)

- prós: nome bonito e agradável, com um significado que combina com a ideia do projeto

- contras: não pertence à mafia do +

**Comment by Bumbleblo** [comment]
Show de bola. Como foi discutido na reunião irei atualizar o nome do projeto.
